version: 2

project_name: mcp-go

builds:
    - skip: true

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - "^ci:"
            - "^chore:"
            - Merge pull request
            - Merge branch

release:
    github:
        owner: XiaoConstantine
        name: mcp-go
